### ISSUE TITLE
[로그인] - 로그인 modal창 관련한 연결 페이지3 - 티스토리 이메일 계정 찾기 페이지

### ISSUE THREAD

**Issue by newfly101** [newfly101/ReactRangers#24]
![image](https://github.com/newfly101/ReactRangers/assets/62008619/66d55571-43c2-4752-b4a3-60e647e2c509)

![image](https://github.com/newfly101/ReactRangers/assets/62008619/f2d8ad96-bf07-4f07-8ca3-3a53009c6a7c)

navigation이 없는 페이지 이기 때문에 App.js 추가 수정 필요함

**Comment by KRjasoncho** [comment]
제작 및 연결 완료
