### ISSUE TITLE
slideCount props전달과정에서 버그발생

### ISSUE THREAD

**Issue by chochohee** [newfly101/ReactRangers#33]
![image](https://github.com/newfly101/ReactRangers/assets/168400614/669b8b21-9722-48c5-8667-c6daef356466)

**Comment by newfly101** [comment]
MainPage에서 나는 버그로, ros-e2에 배정
및 오류 해결 완료
[커밋 browse 부분](https://github.com/newfly101/ReactRangers/commit/5ab9e1e4ad429c5834b1d0f70309cb64728ba911)

**Comment by chochohee** [comment]
skin의 TstorySkin부분에서 사용한 useState의 값이 할당되지 못한 부분 코드 수정

**Comment by chochohee** [comment]
[test](https://github.com/newfly101/ReactRangers/issues/33)
