### ISSUE TITLE
[Story]각 탭 더미데이터 추가

### ISSUE THREAD

**Issue by KRjasoncho** [newfly101/ReactRangers#35]
현재 더미데이터에 '라이프' '여행.맛집' , '문화.연예' 'IT' '스포츠' '시사' 각각 카테고리에 맞는 아이템 박스 데이터가 없습니다. (카드 뉴스 데이터는 존재하므로 각 태그의 리스트 더미데이터를 추가할 예정입니다.

**Comment by newfly101** [comment]
![image](https://github.com/newfly101/ReactRangers/assets/62008619/a36ea254-df2d-4928-83a7-2793cc6a7011)

해당 버튼을 눌렀을때 Network 에서 json url을 웹에다 붙여넣으면
![image](https://github.com/newfly101/ReactRangers/assets/62008619/d012447c-25cd-47d9-b287-b3d0256bc9b2)

다음과 같이 json이 떨어집니다.

이것을 코드의 dummy.js에 붙여넣고 활용 해보시기 바랍니다.

**Comment by KRjasoncho** [comment]
감사합니다 해결했습니다!
