### ISSUE TITLE
button css 상속문제 확인요청드립니다.

### ISSUE THREAD

**Issue by chochohee** [newfly101/ReactRangers#60]
![image](https://github.com/newfly101/ReactRangers/assets/168400614/ae4f6adf-e774-484a-b685-432fb70e7210)

ConvertForm부분 CSS에서 button color 전역상속되어 디버깅 요청드립니다.

**Comment by KRjasoncho** [comment]
푸쉬했습니다! 다른 컴포넌트에서도 전역 상속되는 부분 확인되어서 해당 css들(태그로 속성처리된) class 부여하여 디버깅중에 있습니다. 완료본은 커밋으로 푸쉬하겠습니다.
