### ISSUE TITLE
푸터 가로 스크롤 문제 확인

### ISSUE THREAD

**Issue by ros-e2** [newfly101/ReactRangers#63]
![image](https://github.com/newfly101/ReactRangers/assets/113295030/eec7a07f-0fb9-4597-b831-e43c27fafb54)
코드 확인후 해당 코드때문에 생긴 것을 확인 후 우선 주석 처리 했습니다 
![image](https://github.com/newfly101/ReactRangers/assets/113295030/08c5328c-9ec0-49e7-aed3-5dd557d13d4c)

**Comment by brandysh** [comment]
네 확인 했습니다.
감사합니다
