### ISSUE TITLE
[Feed] Footer.js와 Footer.css가 feed폴더 안에 있습니다.

### ISSUE THREAD

**Issue by KRjasoncho** [newfly101/ReactRangers#64]
![image](https://github.com/newfly101/ReactRangers/assets/166813835/a6252f2d-ce5f-4238-bdff-97b928917315)

feed의 구성요소는 아니므로 따로 footer 폴더로 나누거나, 상위 폴더인 components로 이동이 필요해보입니다.

**Comment by brandysh** [comment]
네 확인했습니다.
수정했습니다
