### ISSUE TITLE
검색어 입력 위치 개선 

### ISSUE THREAD

**Issue by ros-e2** [newfly101/ReactRangers#65]
![image](https://github.com/newfly101/ReactRangers/assets/113295030/d90c8ef7-554c-4bf9-b1b2-baf35e74874c)
![image](https://github.com/newfly101/ReactRangers/assets/113295030/6fb4271d-beec-4c7a-8882-488a22cbacb0)

수정 조금 하긴 했으나 제 페이지 아니여서 확인 부탁 드릴게요!

**Comment by brandysh** [comment]
![image](https://github.com/newfly101/ReactRangers/assets/167677272/74530f37-bbe7-4ec6-b42d-7bf4beafd291)
네 확인했습니다.
감사합니다.
