### ISSUE TITLE
[배포][skin]스킨 페이지 비율 확인

### ISSUE THREAD

**Issue by KRjasoncho** [newfly101/ReactRangers#72]
![image](https://github.com/newfly101/ReactRangers/assets/166813835/3892332a-09be-4f95-a981-4c19cf0a902c)

![image](https://github.com/newfly101/ReactRangers/assets/166813835/ae8d8cd8-a92f-4ea5-a56f-bf80c91e5ba0)

원본 페이지에 비교하면 크롬 기준 100%로 보았을때 각 요소들이 뭔가 작은 느낌이 듭니다.

**Comment by chochohee** [comment]
![image](https://github.com/newfly101/ReactRangers/assets/168400614/279b43c3-1598-4d2e-bfb0-fc2c181bd4ca)

100% 뷰에서 보이는 비율 수정 완료
