### ISSUE TITLE
[Develop관련 건의] 전역 상태 관리 라이브러리 채용(6/19일까지 결정)

### ISSUE THREAD

**Issue by newfly101** [newfly101/ReactRangers#78]
강의에서 비교 설명 하는 부분
1. jotai
2. mobx
3. react-redux
4. recoil
5. zustand

강의에서 설명된 상태 라이브러리 : redux
실제 객체 지향과 더 연관성 높은 상태 라이브러리 : mobx

실제 풀스택 개발자가 더 많이 채용하는 상태 라이브러리는 mobx이지만,
배운 것을 써먹을지, 아니면, 더 쉽고 간결한 mobx를 사용할 것인지에 대한 내용에 대한 의견을 묻고 싶습니다.

comment로 추가 부탁드립니다.

- [ ] redux
- [x] mobx

**Comment by newfly101** [comment]
저는 현업 근무시 mobx로 상태 관리를 하면서 redux를 사용하는 것보다 편하게 상태 관리를 해왔습니다. 실제로 1~5번 비교(구글링) 해보시고, comment 부탁드립니다.

프론트엔드 개발자로만 가면 react-redux를 사용해보는 것이 더 낫습니다.
풀스택 개발자 기준으로는 mobx가 객체지향이기 때문에 @(annotation)을 사용하여 코드의 간결성을 높여주고, redux는 immutable 옵션때문에 객체형태(array, object)인 경우 추가 처리를 통해 코드가 길어집니다.

저의 선택은 mobx가 더 낫다의 의견이고, 근거에 대한 참고 링크를 첨부합니다.
https://techblog.woowahan.com/2599/

**Comment by KRjasoncho** [comment]
redux는 개인 프로젝트에서 적용해서 조금 사용해보았고
![image](https://github.com/newfly101/ReactRangers/assets/166813835/4ccc8a5f-0767-4485-968d-204df1ed1f20)

mobx와 다른 라이브러리는 구글링 통해서 알아보았습니다.  아무래도 상태관리 시스템의 전반적인 로직은 비슷하지만 그 로직을 얼마나 상세하게 다룰 수 있는 지 차이가 있었습니다. 

redux는 단순한 상태를 다루는 데에는 기초 개념만 알아도 큰 문제가 없었지만 form 데이터를 처리하거나, json, opject, array 형태의 자료형을 다루기 시작하면 굉장히 난해하고 복잡한 코드가 시작됩니다. 

다만 이런 상태 관리를 도입하고 시작하는데에 분명히 전역 상태관리의 로직을 이해하고 활용함에 있어서 도움이 되었다고 생각합니다. 

그럼에도 불구하고 저는 mobx를 차용하는 것이 좋다고 생각합니다. 훨씬 간단하고, 러닝커브가 짧고, 복잡한 상태라고 할지라도 어노테이션을 사용해서 축약할 수 있고, 자유도와 활용성도 redux에 비해 낮지 않다고 느껴집니다. 

다만 redux보다는 mobx의 사용자 풀이 작은 것으로 보여집니다.(redux가 구글링시 나오는 자료가 훨씬 많았습니다.) 그렇기에 기존 프로젝트에는 mobx를 차용하지만, 각 개인의 팀원분들께서는 redux 역시 간단한 개념과 로직을 이해한 상태로 mobx를 차용할 수 있도록 개별의 준비가 필요해보입니다.

**Comment by newfly101** [comment]
mobx 6 버전부터 annotation이 지원하지 않는데, 현재 구현된 부분은
class형 store과
const형 store 두가지가 구현되어 있습니다.

사용하는 method는 
1. `useLocalObservable(() => {})`
2. `return makeAutoObservable({})`
3. `export default class ForumStore2 {}`

이니 잘 코드 뜯어보시고, 참고하셔서 공부해보시기 바랍니다.
